spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/studs
    username: s285317
    password: 
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database: postgresql
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-circular-references: true

queueName: mail

camunda:
  bpm:
    database:
      schema-update: true
      table-prefix: s285317.
      type: postgres
