spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/studs
    username: s285317
    password: vqo204
    driverClassName: org.postgresql.Driver


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    database: postgresql